/*****************************************************************************************
 *                                                                                       *
 * Wormhole                                                                              *
 *                                                                                       *
 * Copyright (c) 2026-2026                                                               *
 *                                                                                       *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this  *
 * software and associated documentation files (the "Software"), to deal in the Software *
 * without restriction, including without limitation the rights to use, copy, modify,    *
 * merge, publish, distribute, sublicense, and/or sell copies of the Software, and to    *
 * permit persons to whom the Software is furnished to do so, subject to the following   *
 * conditions:                                                                           *
 *                                                                                       *
 * The above copyright notice and this permission notice shall be included in all copies *
 * or substantial portions of the Software.                                              *
 *                                                                                       *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,   *
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A         *
 * PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT    *
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF  *
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE  *
 * OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                                         *
 ****************************************************************************************/

import {
  updateActiveSessionStatus,
  updateCurrentActiveUsers,
  updateCurrentHost,
  updateUsage
} from './adminApi';
import {
  Peer,
  ConnectionStatus,
  MessageType,
  CurrentProtocolVersion
} from './types/types';
import { LDEBUG, LERROR } from './utils';

/**
 * A named room that manages a group of connected peers. One peer may act as the host,
 * controlling what all participants see, which simulation time is used, and which Lua
 * scripts execute on all connected OpenSpace instances.
 */
export class Session {
  /**
   * The unique name of this session. Peers must must provide this name during
   * authentication to join. Maximum 255 ASCII characters.
   */
  private name: string;

  /**
   * The clear-text password that peers need to provide to connect. This password has a
   * maximum length of 65535 characters and can consist only of ASCII characters.
   * An empty string means the room is public and any password is accepted.
   */
  private password: string;

  /**
   * The clear-text password for assuming hostship. The host password can have a maximum
   * length of 65535 characters and can consist only of ASCII characters.
   */
  private hostPassword: string;

  /**
   * A unique ID for this session, generated by the Firebase database provider.
   */
  private id: string | null = null;

  /**
   * The list of all peers currently connected to this session. Peers are appended on
   * successful authentication and removed when they disconnect or produce an error.
   */
  private peers: Peer[] = [];

  /**
   * The id of the current host. Note that this is **not** the location of this
   * peer in the `peers` list, but its `id`, which might be different under some
   * circumstances.
   */
  private currentHostId: number | null = null;

  /**
   * Creates a new Session.
   *
   * @param name The unique name of this session
   * @param password The password peers must provide to join. Maximum 65535 ASCII
   * characters.
   * @param hostPassword The password peers must provide to claim hostship. Maximum 65535
   * ASCII characters.
   * @param id The unique ID assigned by the Firebase database provider, or null if not
   * yet set
   */
  constructor(
    name: string,
    password: string | null,
    hostPassword: string,
    id: string | null = null
  ) {
    this.name = name;
    this.password = password ?? '';
    this.hostPassword = hostPassword;
    if (id) {
      this.id = id;
    }
  }

  /**
   * @return The metadata of this session
   */
  public getSessionMetadata() {
    return {
      sessionName: this.name,
      password: this.password,
      hostPassword: this.hostPassword,
      id: this.id
    };
  }

  /**
   * Sets the unique ID of this session.
   *
   * @param id The unique ID assigned to this session
   */
  public setSessionID(id: string): void {
    this.id = id;
  }

  /**
   * Forcibly closes the session, disconnecting all connected peers.
   */
  public stop(): Promise<void> {
    return new Promise((resolve) => {
      let disconnectCount = 0;

      if (this.peers.length === 0) {
        resolve();
      }

      const checkAllDisconnected = () => {
        disconnectCount += 1;
        if (disconnectCount === this.peers.length) {
          resolve();
        }
      };

      for (const peer of this.peers) {
        // Handle if socket does not end properly
        peer.socket.on('error', (err) => {
          LDEBUG(
            `Session ${this.id}: error disconnecting peer #${peer.id} ('${peer.name}')`,
            err
          );
          checkAllDisconnected();
        });

        peer.socket.end(() => {
          checkAllDisconnected();
        });
      }
    });
  }

  /**
   * Handles the disconnection of a peer. We remove the peer from the list of connected
   * peers and free up the ID slot. If the peer that disconnected was the host, we
   * inform all connected peers that they no longer have a host.
   *
   * @param peer The peer that just disconnected
   */
  public onEnd(peer: Peer): void {
    // Find the index in the peer list of the peer that disconnected
    const idx = this.peers.findIndex((p: Peer) => p.id === peer.id);
    if (idx === -1) {
      LERROR(
        `Session '${this.id}': could not find peer with id #${peer.id} ` +
          `('${peer.name}') on disconnect`
      );
      return;
    }
    this.peers.splice(idx, 1);

    // Remove hostship if the host disconnected
    if (peer.id === this.currentHostId) {
      this.removeHostship();
    }

    // Update the number of connections
    this.sendNumberOfConnections();

    LDEBUG(`Session '${this.id}': ${this.peers.length} connection(s) remaining`);
  }

  /**
   * Handle incoming data from the provided peer, we only forward the data along to
   * other peers if it comes from the host.
   *
   * @param data The payload of the data message
   * @param peer The peer from which this message is coming
   */
  public handleData(data: Buffer, peer: Peer): void {
    // Check if this peer is the current host
    if (peer.id === this.currentHostId) {
      if (peer.status !== ConnectionStatus.Host) {
        LERROR(
          `Session '${this.id}': peer #${peer.id} ('${peer.name}')  matches ` +
            `currentHostId but has status ${peer.status}, expected Host ` +
            `(${ConnectionStatus.Host})`
        );
      }

      const message = this.buildMessage(MessageType.Data, data);
      this.peers.forEach((peer: Peer) => {
        if (peer.status === ConnectionStatus.ClientWithHost) {
          this.writeMessage(peer, message);
        }
      });
    }
  }

  /**
   * Handles an incoming hostship request message by the peer. If the message contains
   * the correct host password, the peer is promoted to hostship and the previous host
   * is demoted.
   *
   * @param data The payload of the hostship request message
   * @param peer The peer from which this message arrived
   */
  public handleHostshipRequest(data: Buffer, peer: Peer): void {
    LDEBUG(`Session '${this.id}': peer #${peer.id} ('${peer.name}') requested hostship`);

    const dv = new DataView(
      data.buffer.slice(data.byteOffset, data.byteOffset + data.byteLength)
    );
    let offset = 0;

    const passwordLength = dv.getUint16(offset, true);
    offset += Uint16Array.BYTES_PER_ELEMENT;
    if (passwordLength === 0) {
      // No password was given so we don't do anything
      LDEBUG(`Session '${this.id}': invalid host password length`);
      return;
    }

    const password = data.subarray(offset, offset + passwordLength).toString('utf-8');
    if (password !== this.hostPassword) {
      // Wrong password so we don't do anything
      LDEBUG(
        `Session '${this.id}': peer #${peer.id} ('${peer.name}') provided incorrect ` +
          `host password`
      );
      return;
    }

    if (peer.id === this.currentHostId) {
      LDEBUG(`Session '${this.id}': peer #${peer.id} ('${peer.name}') is already host`);
      return;
    }

    this.assignHost(peer);
  }

  /**
   * Handles an incoming hostship resignation by the peer. If the peer is the current
   * host, we remove the hostship and inform all connected peers that they lost their
   * host.
   *
   * @param peer The peer from which this message arrived
   */
  public handleHostshipResignation(peer: Peer): void {
    LDEBUG(`Session '${this.name}': peer #${peer.id} ('${peer.name}') resigned hostship`);

    // Only remove the host if it was the host peer that requested the resignation
    if (peer.status === ConnectionStatus.Host) {
      this.removeHostship();
    }
  }

  /**
   * Checks whether the provided password grants access to this session. Any empty room
   * password means the room is public and any password is accepted.
   *
   * @param password The room password provided by the peer
   * s True if the password is correct, false otherwise
   */
  public isPasswordValid(password: string): boolean {
    return this.password === '' || password === this.password;
  }

  /**
   * Registers an already-validated peer into the session: adds it to the list of
   * connected peers, and promotes it to host if it provided the correct host password
   * and no host is currently assigned. The caller is responsible for having confirmed
   * the room password, and an existing `peer.id` already being set.
   *
   * @param peer The peer to register
   * @param hostPassword The host password provided by the peer, or null if none was given
   */
  public registerPeer(peer: Peer, hostPassword: string | null): void {
    // We can add this peer to the list of all peers in the group
    this.peers.push(peer);

    // If there is currently no host and this peer provided the host password
    // we promote them to hostship
    if (this.currentHostId === null && hostPassword === this.hostPassword) {
      LDEBUG(
        `Session '${this.name}': peer #${peer.id} ('${peer.name}') promoted to host`
      );
      this.assignHost(peer);
    } else {
      LDEBUG(
        `Session '${this.name}': peer #${peer.id} ('${peer.name}') registered as client`
      );
      peer.status =
        this.currentHostId === null
          ? ConnectionStatus.ClientWithoutHost
          : ConnectionStatus.ClientWithHost;

      this.sendConnectionStatus(peer);
    }

    this.sendNumberOfConnections();
    updateUsage(this.id!);
  }

  /**
   * Construct a complete message buffer including the message header and provided payload
   * data.
   *
   * @param messageType The type of message to construct
   * @param payload The payload of the message
   * @return A buffer object holding the constructed message
   */
  private buildMessage(messageType: MessageType, payload: Buffer): Buffer {
    const buffer = Buffer.alloc(
      'OS'.length + // OS prefix
        Uint8Array.BYTES_PER_ELEMENT + // protocol version number
        Uint8Array.BYTES_PER_ELEMENT + // message type identifier
        Uint32Array.BYTES_PER_ELEMENT + // payload size in bytes
        payload.byteLength // payload
    );

    const dv = new DataView(buffer.buffer, buffer.byteOffset, buffer.byteLength);
    let offset = 0;

    // Set OS header
    dv.setUint8(offset, 'OS'.charCodeAt(0));
    offset += Uint8Array.BYTES_PER_ELEMENT;
    dv.setUint8(offset, 'OS'.charCodeAt(1));
    offset += Uint8Array.BYTES_PER_ELEMENT;

    // Protocol version
    dv.setUint8(offset, CurrentProtocolVersion);
    offset += Uint8Array.BYTES_PER_ELEMENT;

    // Message type
    dv.setUint8(offset, messageType);
    offset += Uint8Array.BYTES_PER_ELEMENT;

    // Message size
    dv.setUint32(offset, payload.byteLength, true);
    offset += Uint32Array.BYTES_PER_ELEMENT;

    // Copy the payload into the message
    payload.copy(buffer, offset);
    return buffer;
  }

  /**
   * Write the `message` to the provided `peer`.
   *
   * @param peer The peer that will recieve the message
   * @param message The message payload data that is sent
   */
  private writeMessage(peer: Peer, message: Buffer): void {
    LDEBUG(`Session '${this.id}': sending message to peer #${peer.id} ('${peer.name}')`);
    peer.socket.write(message);
  }

  /**
   * Send a message to the provided peer of the provided `messageType` with the specified
   * `payload` data.
   *
   * @param peer The peer that will recieve the message
   * @param messageType The type of message that will be sent
   * @param payload The payload of the data that is sent
   */
  private sendMessage(peer: Peer, messageType: MessageType, payload: Buffer): void {
    this.writeMessage(peer, this.buildMessage(messageType, payload));
  }

  /**
   * Send a connection status message to the provided peer.
   *
   * @param peer The peer that will recieve the connection status message
   */
  private sendConnectionStatus(peer: Peer): void {
    const host = this.currentHost();
    const currentHostName = host === null ? '' : host.name;

    const buffer = Buffer.alloc(
      Uint8Array.BYTES_PER_ELEMENT + // Status
        Uint8Array.BYTES_PER_ELEMENT + // Length of host
        currentHostName.length // Host name
    );

    const dv = new DataView(buffer.buffer, buffer.byteOffset, buffer.byteLength);
    let offset = 0;

    // Set the connection status of the peer as known by the server
    dv.setUint8(offset, peer.status);
    offset += Uint8Array.BYTES_PER_ELEMENT;

    // The length of the host name
    dv.setUint8(offset, currentHostName.length);
    offset += Uint8Array.BYTES_PER_ELEMENT;

    // Insert the name of the current host
    buffer.write(currentHostName, offset, 'ascii');

    this.sendMessage(peer, MessageType.ConnectionStatus, buffer);
  }

  /**
   * Send the number of connections to all connected peers.
   */
  private sendNumberOfConnections(): void {
    LDEBUG(`Session '${this.id}': sending number of connections to all peers`);

    const buffer = Buffer.alloc(Uint32Array.BYTES_PER_ELEMENT); // Number of connections
    const dv = new DataView(buffer.buffer, buffer.byteOffset, buffer.byteLength);
    dv.setUint32(0, this.peers.length, true);

    const message = this.buildMessage(MessageType.NConnections, buffer);
    this.peers.forEach((peer: Peer) => this.writeMessage(peer, message));
    // Update the server status depending on if there still are any users connected
    const isServerActive = this.peers.length > 0;
    updateActiveSessionStatus(this.id!, isServerActive);
    updateCurrentActiveUsers(this.id!, this.peers.length);
  }

  /**
   * @return The current host of the group or null if there is no host assigned
   */
  private currentHost(): Peer | null {
    if (this.currentHostId === null) {
      return null;
    }

    const idx = this.peers.findIndex((peer: Peer) => peer.id === this.currentHostId);
    if (idx === -1) {
      LDEBUG(`Session '${this.id}': could not find host with id ${this.currentHostId}`);
      return null;
    }

    return this.peers[idx];
  }

  /**
   * Mark the provided newHost peer as the new host of the group and remove the hostship
   * of the previous host. Inform all connected peers about the change in hostship.
   *
   * @param newHost The peer to be promoted to the new host
   */
  private assignHost(newHost: Peer): void {
    // If we currently have a host, we need to demote them
    if (this.currentHostId !== null) {
      let oldHost = this.currentHost()!; // Host id cannot be null here
      oldHost.status = ConnectionStatus.ClientWithHost;
    }

    // Promote the provided peer to host
    this.currentHostId = newHost.id;
    newHost.status = ConnectionStatus.Host;

    // Update others about the new host
    this.peers.forEach((peer: Peer) => {
      // If there was no host before, let them know about the new host
      if (peer.status === ConnectionStatus.ClientWithoutHost) {
        peer.status = ConnectionStatus.ClientWithHost;
      }
      this.sendConnectionStatus(peer);
    });

    updateCurrentHost(this.id!, newHost.name);
  }

  /**
   * If the group has a host, we remove the hostship and inform all connected peers that
   * there is no host anymore.
   */
  private removeHostship(): void {
    // If we don't have a host, we don't need to do anything
    if (this.currentHostId === null) {
      return;
    }

    // Remove host information on server side
    this.currentHostId = null;

    // Inform all peers that we no longer have a host, this includes the recently
    // removed host aswell
    this.peers.forEach((peer: Peer) => {
      peer.status = ConnectionStatus.ClientWithoutHost;
      this.sendConnectionStatus(peer);
    });

    updateCurrentHost(this.id!, 'null');
  }
}
